# Generated by Django 4.1.1 on 2023-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ormmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('sal', models.IntegerField()),
            ],
        ),
    ]
