# Generated by Django 4.1.1 on 2024-05-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
